#!/bin/bash

TL "Start: $SrvReq/WkFloRcv"

if [[ ! -e "/srv/run/wkFlo/hstWkFloRcv.fifo" ]]; then
    mkfifo /srv/run/wkFlo/hstWkFloRcv.fifo;
    
#xx    $SrvBin/fifoRcvLib-01.sh &
    $SrvBin/WkFloMainRcv.sh &
    
else TL "** WkFloRcv ALREADY runing **"
fi
TL "End: $SrvReq/WkFloRcv"
