#!/bin/bash

#log "Start: WfDbDmpCB - from exported log()"
#log () { echo "`date +%Y/%m/%d-%T` - $@" >> $LogFQPFN; }
#log " from re def of log"

log "Start: $0 - $@"

env > /tmp/env.txt

export SqlSvrID=$1  WkFloTkn=$2  xc=$3  tmpGP=$4; shift 4;
export WfTknBasHP=$SrvWkFlo/svrCB/$SqlSvrID/WfDbDmpCB # /{G,B,w8}
log "[WfDbDmpCB] WfTknBasHP >> $WfTknBasHP"
log "[WfDbDmpCB] WkFloTkn >> $WkFloTkn"

if [[ -e $WfTknBasHP/w8/$WkFloTkn ]]; then 
    log "[WkFlo] WfDbDmpCB() - Found tkn file: $WfTknBasHP/w8/$WkFloTkn - Loading..."
    . $WfTknBasHP/w8/$WkFloTkn
    log "[WfDbDmpCB] Loaded token env: $WkFloTkn "
    log "[WfDbDmpCB] WkStp: $WkStp   WkStpCbG: $WkStpCbG    WkStpCbB: $WkStpCbB"
else
    log "[WkFlo] WfDbDmpCB() - ** MISSING tkn file: $WfTknBasHP/w8/$WkFloTkn "
fi

if [[ -e $SrvWkFlo/svrByID/$SqlSvrID ]]; then 
    log "[WkFlo] WfDbDmpCB() - Found svr file: $SrvWkFlo/svrByID/$SqlSvrID - Loading..."
    . $SrvWkFlo/svrByID/$SqlSvrID  # Sym link to [SqlSvr] guestEnv.sh
    log "[WfDbDmpCB] Loaded svr env: $SqlSvrID"
else
    log "[WkFlo] WfDbDmpCB() - ** MISSING svr file: $SrvWkFlo/svrByID/$SqlSvrID"
fi

log "[WfDbDmpCB]   $SqlSvrID $WkFloTkn   $xc  $tmpGP"
log "[WfDbDmpCB after Tkn load] WfDbDmpCB - Hst Pth: $KnBasHP$tmpGP"
log "[WfDbDmpCB after Tkn load] WfDbDmpCB - ls: `ls $KnBasHP$tmpGP`"
		# @@ Load WkStp & WkStpKls, Confirm G|B,  call G()|B(), __? exit!  <<<<<<<<<<<<< 

log "END: WfDbDmpCB"
